# This Dockerfile builds the API only.

FROM python:3
WORKDIR /app

COPY api/. ./

# 安装 Python 依赖
RUN pip install --no-cache-dir -r ./requirements.txt

# 指定 Flask 运行端口
EXPOSE 5000

# 运行 Flask 应用
CMD ["python", "app.py"]
